#!/bin/bash


#IF statement for GNU compiler issue
export GCC_VERSION=$(/usr/bin/gcc -dumpfullversion | awk '{print$1}')
export GFORTRAN_VERSION=$(/usr/bin/gfortran -dumpfullversion | awk '{print$1}')
export GPLUSPLUS_VERSION=$(/usr/bin/g++ -dumpfullversion | awk '{print$1}')

export GCC_VERSION_MAJOR_VERSION=$(echo $GCC_VERSION | awk -F. '{print $1}')
export GFORTRAN_VERSION_MAJOR_VERSION=$(echo $GFORTRAN_VERSION | awk -F. '{print $1}')
export GPLUSPLUS_VERSION_MAJOR_VERSION=$(echo $GPLUSPLUS_VERSION | awk -F. '{print $1}')

export version_10="10"

if [ $GCC_VERSION_MAJOR_VERSION -ge $version_10 ] || [ $GFORTRAN_VERSION_MAJOR_VERSION -ge $version_10 ] || [ $GPLUSPLUS_VERSION_MAJOR_VERSION -ge $version_10 ]
then
  export fallow_argument=-fallow-argument-mismatch
  export boz_argument=-fallow-invalid-boz
else
  export fallow_argument=
  export boz_argument=
fi


export FFLAGS=$fallow_argument
export FCFLAGS=$fallow_argument


echo "##########################################"
echo "FFLAGS = $FFLAGS"
echo "FCFLAGS = $FCFLAGS"
echo "##########################################"



export GFORTRAN_COMP=gfortran
export LIB_CFITSIO=../others/cfitsio/lib
#modules are compiled apart
cd ./routines_f90/
rm *.o *.mod

$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./common.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./fits.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./instrument_harps.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./instrument_harpn.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./levenberg_marquardt.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./levenberg_marquardt_mod5V.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./ccf.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./gaussian_fit.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./chebyshev_fit.f90
$GFORTRAN_COMP -O2 -funroll-loops $FFLAGS -c ./poly_fit.f90


cd ..
$GFORTRAN_COMP -O2 -funroll-loops -fexpensive-optimizations $FFLAGS ./routines_f90/*.o -J ./routines_f90/  harpn_input2pams.f90 -o ./harpn_input2pams.e -lblas -llapack -lm -lcfitsio
$GFORTRAN_COMP -O2 -funroll-loops -fexpensive-optimizations $FFLAGS ./routines_f90/*.o -J ./routines_f90/  harps_input2pams.f90 -o ./harps_input2pams.e -lblas -llapack -lm -lcfitsio
